<?php
/**
 * Created by PhpStorm.
 * User: wangluyu
 * Date: 18/8/26
 * Time: 上午12:08
 */

namespace app\plugin\plugins\book;


use app\plugin\Plugin;

class Book extends Plugin
{
    public static function install()
    {
        return parent::install(); // TODO: Change the autogenerated stub
    }
    public static function update()
    {
        return parent::update(); // TODO: Change the autogenerated stub
    }
    public static function uninstall()
    {
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }
}