<?php
/**
 * Created by PhpStorm.
 * User: wangluyu
 * Date: 18/8/28
 * Time: 下午10:46
 */

namespace app\plugin\plugins\wechat;


use app\plugin\Plugin;

class WeChat extends Plugin
{
    public static function install()
    {
        return parent::install(); // TODO: Change the autogenerated stub
    }
    public static function uninstall()
    {
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }
    public static function update()
    {
        return parent::update(); // TODO: Change the autogenerated stub
    }
}